app.py
import os
import logging
from flask import Flask, render_template, send_file
from dotenv import load_dotenv
from controllers.home_controller import home_bp
from controllers.about_controller import about_bp
from logger_config import logger

# Load environment variables from .env file
load_dotenv()

app = Flask(__name__)

# Register blueprints
app.register_blueprint(home_bp)
app.register_blueprint(about_bp)


@app.errorhandler(404)
def page_not_found(e):
    logger.warning("404 Error: Page not found")
    return render_template('404.html'), 404


@app.errorhandler(500)
def internal_server_error(e):
    logger.error(f"500 Error: {str(e)}")
    return render_template('500.html'), 500


@app.route('/offline')
def offline():
    return render_template('offline.html')


@app.route('/static/js/service-worker.js')
def service_worker():
    response = send_file('static/js/service-worker.js')
    # Allow the service worker to control the root scope
    response.headers['Service-Worker-Allowed'] = '/'
    return response


if __name__ == '__main__':
    app.run(debug=os.getenv('FLASK_DEBUG', 'false').lower() == 'true')

controllers/about_controller.py
# controllers/about_controller.py
from flask import Blueprint, render_template

about_bp = Blueprint('about', __name__)

@about_bp.route('/about')
def about():
    return render_template('about.html')

controllers/home_controller.py
# controllers/home_controller.py
from flask import Blueprint, render_template, request, jsonify
import spacy
import numpy as np
from index import generate_questions
from logger_config import logger

# Initialize Spacy model
nlp = spacy.load("en_core_web_sm")

home_bp = Blueprint('home', __name__)


@home_bp.route('/')
def home():
    return render_template('index.html')

# Route to handle question generation


@home_bp.route('/api/generate', methods=['POST'])
def generate():
    try:
        # Get the note from the form
        note = request.form.get('note')
        if (note == ''):
            return jsonify({
                'status': 'fail',
                'errors': ['Note field is required']
            })

        # Process the note to generate questions (placeholder logic)
        questions = generate_questions(note)

        return jsonify({
            'status': 'success',
            'questions': questions
        })
    except Exception as e:
        error_info = {
            "error": str(e),
            "type": type(e).__name__
        }

        logger.error(f"500 Error: {error_info}")

        return jsonify({
            'status': 'fail',
            'errors': ["Something went wrong!"]
        })

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<h1>About Page</h1>
{% endblock %}

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="An advanced, human-like question generation system built from scratch. This project dynamically
    learns from your input notes and data, mimicking human intelligence to generate insightful questions, fully
    personalized to the text you provide. No templates, just pure learning and reasoning! 🌟">
    <title>{% block title %}Questions Generator{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="manifest" href="{{ url_for('static', filename='manifest.json') }}">

    <link rel="apple-touch-icon" sizes="180x180"
        href="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32"
        href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16"
        href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">

</head>

<body>

    {% include 'header.html' %}

    <div class="container mt-5 min-vh-100">
        {% block content %}{% endblock %}
    </div>

    {% include 'footer.html' %}

    <!-- Bootstrap JS and dependencies (optional) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.6/dist/umd/popper.min.js" defer></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" defer></script>

    {%block scripts%}{%endblock%}
    <script src="{{ url_for('static', filename='js/app.js') }}" defer></script> <!-- External JS file -->
</body>

</html>

templates/footer.html
<footer class="bg-light text-center text-lg-start mt-5">
    <div class="text-center p-3">
        © 2024 Questions Generator
    </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light py-3">
    <a class="navbar-brand" href="/">Questions Generator</a>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('home.home') }}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('about.about') }}">About</a>
            </li>
            <li class="ml-4">
                <button class="btn btn-dark rounded-pill" id="installButton" style="display: none;">Download</button>
            </li>
        </ul>
    </div>
</nav>

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Welcome to Questions Generator AI!</h1>
<p>An advanced, human-like question generation system built from scratch. This project dynamically
    learns from your input notes and data, mimicking human intelligence to generate insightful questions, fully
    personalized to the text you provide. No templates, just pure learning and reasoning! 🌟</p>

<form id="questionForm" method="post" class="mt-5">
    <div class="alert alert-danger" id="validationAlert" style="display: none;" role="alert"></div>
    <div class="mb-3">
        <label for="note" class="form-label">Note</label>
        <textarea class="form-control" name="note" id="note" rows="10" data-min-length="10" data-required="true"
            data-required-message="Note field is required."
            data-min-length-message="Note must be at least 10 characters long."></textarea>
    </div>
    <button type="submit" class="btn btn-dark">Generate</button>
</form>

<div id="questionsContainer" style="display: none;" class="mt-4 mb-4">
    <h2>Generated Questions:</h2>
    <ul id="questionsList"></ul>
</div>

{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/home.js') }}" defer></script> <!-- External JS file -->
<script src="{{ url_for('static', filename='js/formValidator.js') }}" defer></script> <!-- External JS file -->
{% endblock %}

templates/offline.html
{% extends "base.html" %}
{% block title %}500{% endblock %}
{% block content %}
<div class="d-flex flex-column align-items-center justify-content-center text-center">
    <h1 class="display-4 text-dark">Oops! Seems your offline</h1>
    <p class="lead">Please try again later by checking your connection.</p>
</div>
{% endblock %}